services:
  mysql:
    image: mysql:8.4
    container_name: logistics-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "${MYSQL_PORT}:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: logistics-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"

  backend:
    image: logistics-backend
    container_name: logistics-backend
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379

    ports:
      - "${PORT}:5000"

    depends_on:
      - mysql
      - redis
  worker:
    image: logistics-backend
    container_name: logistics-worker
    restart: unless-stopped

    command: npm run jobs

    env_file:
      - .env

    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
